const express = require('express');
const router  = express.Router();
const { getNotices, createNotice, updateNotice, deleteNotice } = require('../controllers/notice.controller');
const { authenticate } = require('../middleware/auth.middleware');
router.use(authenticate);
router.get('/',       getNotices);
router.post('/',      createNotice);
router.put('/:id',    updateNotice);
router.delete('/:id', deleteNotice);
module.exports = router;
